"""Canonical events and the recording that holds them."""

from .events import (
    Click,
    Comment,
    Drag,
    ElementRef,
    Event,
    HotKey,
    KeyStroke,
    MouseMove,
    Origin,
    Pause,
    Scroll,
    Sync,
    Target,
    TextInput,
    WaitForElement,
    WaitForIdle,
    WaitForWindow,
    WindowActivate,
    WindowRef,
    event_from_dict,
)
from .recording import Environment, Recording

__all__ = [
    "Click",
    "Comment",
    "Drag",
    "ElementRef",
    "Environment",
    "Event",
    "HotKey",
    "KeyStroke",
    "MouseMove",
    "Origin",
    "Pause",
    "Recording",
    "Scroll",
    "Sync",
    "Target",
    "TextInput",
    "WaitForElement",
    "WaitForIdle",
    "WaitForWindow",
    "WindowActivate",
    "WindowRef",
    "event_from_dict",
]
